// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/command-center/ScorecardStrip.tsx": () => import("../components/mockups/command-center/ScorecardStrip.tsx"),
  "./components/mockups/command-center/SidebarSplit.tsx": () => import("../components/mockups/command-center/SidebarSplit.tsx"),
  "./components/mockups/command-center/TopDownFlow.tsx": () => import("../components/mockups/command-center/TopDownFlow.tsx")
};
